### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jjmaturino** [roygreenfeld/django-crash-course#131] opened 2020-02-22 04:27 UTC
## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile.

## Location within the Book

* Chapter or Appendix:15
* Section:5
* Subsection:1

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> As I was reading the beta of your book, I came across a typo.

It says “If yoweu have used Django-crash-starter before”

**Comment by quique** [comment] 2020-02-22 13:02
Duplicate of #122

**Closed** 2020-02-22 18:33 UTC
