### ISSUE TITLE
41.7 Commit message

### ISSUE THREAD

**Issue by rohithpr** [roygreenfeld/django-crash-course#141] opened 2020-02-25 08:03 UTC
## Location within the Book

* Chapter or Appendix: 41
* Section: 41.7 Commit Our Work
* Subsection:

## Description 

> `git commit -m "Create a CheeseFactory and use it in Cheese model test"`

In section "39.5 Commit the Changes" we already have a commit for creating the factory: `git commit -m "Add a cheese factory"`.

So in "41.7" the commit message should only be "Use CheesyFactory in Cheese model test".

**Comment by quique** [comment] 2020-02-25 12:11
Duplicate of #138

**Closed** 2020-02-25 13:15 UTC
