### ISSUE TITLE
Fix typo in Extended HomepageView section

### ISSUE THREAD

**Issue by omaciel** [roygreenfeld/django-crash-course#47] opened 2020-02-12 22:23 UTC
## Location within the Book

* Chapter or Appendix: 11
* Section: 11.3
* Subsection:

## Description 

> There, you defined a context variable called my_statement. You assigned it the value of hello

Should be

> There, you defined a context variable called my_statement. You assigned it the value of Nice to see you!

**Comment by pydanny** [comment] 2020-02-12 22:39
Duplicate of #43

**Closed by pydanny** 2020-02-12 22:39 UTC
Labels: duplicate
