### ISSUE TITLE
Section 17.7 - invalid syntax

### ISSUE THREAD

**Issue by magnusvaughan** [roygreenfeld/django-crash-course#96] opened 2020-02-16 19:27 UTC
## Location within the Book

* Chapter or Appendix: 17
* Section: 17.7
* Subsection:

## Description 

```
When I run python manage.py migrate I get the following error: 

 File "/Users/magnusvaughan/tutorials/django_crash_course/everycheese/everycheese/users/urls.py", line 3, in <module>
    from everycheese.users.views import (
  File "/Users/magnusvaughan/tutorials/django_crash_course/everycheese/everycheese/users/views.py", line 22
    UpdateView):
    ^
SyntaxError: invalid syntax
```

**Comment by magnusvaughan** [comment] 2020-02-16 19:31
The relevant class definition from the error message begins like this for me:

```
class UserUpdateView(LoginRequiredMixin
                                UpdateView):
    fields = ['name', ]
```

Fixed by changing this to 

```
class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['name', ]
```

**Comment by quique** [comment] 2020-02-16 19:41
Duplicate of #87

**Closed** 2020-02-16 21:10 UTC
